### PR TITLE
Preload classes

### PR DESCRIPTION
**Pull request by rlepinski**
Preloads all the classes from the jar files on init. The classes seem to be cached between build so this significantly increases build times for sequential builds.

Build times before:
- Clean & Build : ~4 mins
- Sequential Build : ~2 seconds
- Modify the doc with several references & Build: ~4 mins

Build times after:
- Clean & Build : ~30 seconds
- Sequential Build: ~2 seconds
- Modify the doc with several references & Build: ~7 seconds
- Modify a doc with zero javaref references & Build: ~7 seconds

### CODE REVIEW

**Comment by bluekeyes** [comment]
Thanks for submitting this, as it inspired me to do some more testing and pointed me in the right direction for fixing the slowness. Unfortunately, I don't think preloading all classes is the right solution. My intuition was that it's wasteful (both in time and in memory) to load full jars when most documents will link to a small fraction of the available classes and my testing showed that preloading was significantly slower than the existing method. My guess is that your project has a total classes to unique references ratio that is much smaller than mine (1843:1), so preloading is actually faster for you.

The real cost with the current method is the fact that potentially every jar on the classpath is opened and closed for every class search; once a jar is open, loading a single class is fast.

My tests used the `ClassLoader` in isolation. The classpath contained the Java 7 runtime jar (18584 classes), Guava 18 (1690 classes), and a local folder with 4 class files. I used the `timeit` module to run 10 iterations of a loop that constructed a `ClassLoader` instance and loaded 11 arbitrary classes:

```
testing current: ..........
result: 2.81314129829s per iter

testing pre-open: ..........
result: 0.297156691551s per iter

testing preload: ..........
result: 45.108049202s per iter
```

Since pre-opening is much faster, I'll clean up my code and then make a new release later this weekend that includes this change and your previous performance fix. Thanks again for contributing!

**Comment by rlepinski** [comment]
Just tested your changes and it is indeed significantly faster than before. Every build is now around ~25 seconds (down from 4 mins).

I agree that my solution was wasteful and probably more time consuming for the majority of use cases. However it is still significantly faster for me to preload all the classes for sequential builds. I think we can still improve performance if we cache class results between builds (maybe it already does?) and instead of opening up every jar on start only open the jars (and then leave them open) if we have to do a class look up. That should prevent touching the jars for sequential builds if the new build does not contain a unique class reference.

**Comment by bluekeyes** [comment]
Classes should already be cached between builds - the `ClassLoader` is part of the Sphinx environment and the `packages` dict should be pickled and restored along with everything else. A PR that opens jars lazily is welcome if you have time to work on it.

**Comment by rlepinski** [comment]
Actually after testing again it seems that sequential builds are around 5 seconds... I must of accidentally cleaned during my initial testing.

Thanks!

**Pull request closed without merging**
